"""Add task status.

Revision ID: 8229c67c9ab3
Revises: e421fd355ee7
Create Date: 2024-04-01 21:51:21.387678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8229c67c9ab3'
down_revision: Union[str, None] = 'e421fd355ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    taskstatus = sa.Enum('todo', 'inProgress', 'completed', name='taskstatus')
    taskstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('tasks', sa.Column('status', sa.Enum('todo', 'inProgress', 'completed', name='taskstatus'), nullable=True))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_column('tasks', 'status')
    sa.Enum(name='taskstatus').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
