"""Change task column name

Revision ID: e421fd355ee7
Revises: 2d799f47ffaf
Create Date: 2024-03-28 20:04:16.760501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e421fd355ee7'
down_revision: Union[str, None] = '2d799f47ffaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
